name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project (allow failure so subsequent steps run)
        run: npm run build || true

      - name: Show build output (debug - always)
        if: ${{ always() }}
        run: |
          echo "=== printing dist/ contents ==="
          ls -la dist || echo "dist folder does not exist"

      - name: Upload production-ready build files (always upload even if build failed)
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && always() }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Ensure dist has something to publish (create placeholder if empty)
        run: |
          if [ ! -d "dist" ] || [ -z "$(ls -A dist 2>/dev/null)" ]; then
            echo "No build files found — creating placeholder index.html"
            mkdir -p dist
            cat > dist/index.html <<'HTML'
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Placeholder build</title>
  </head>
  <body>
    <h1>Placeholder: original build failed</h1>
    <p>Check the Actions logs for build errors.</p>
  </body>
</html>
HTML
          else
            echo "dist folder contains files; proceeding to deploy"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
